version: '3.9'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quoteorder
    ports: ['5432:5432']
  redis:
    image: redis:7
    ports: ['6379:6379']
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    ports: ['8000:8000']
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs,eventbridge,iam,sts,cloudwatch
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - '4566:4566'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
